# This contains params to be used by the stages to train or predict

prepare:
  split: 0.20
  seed: 2021

featurize:
  max_features: 3500
  ngrams: 2

train:
  seed: 2021
  n_est: 200
  min_split: 20
